# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/yolo_v8_segmentation',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/yolo_v8_segmentation',
                'lib_path': 'yolo_v8_segmentation'},
  'syms': {'yolo_v8_segmentation.core': {'yolo_v8_segmentation.core.foo': ('core.html#foo', 'yolo_v8_segmentation/core.py')}}}
