# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/yolo_v8_segmentation',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/yolo_v8_segmentation',
                'lib_path': 'yolo_v8_segmentation'},
  'syms': { 'yolo_v8_segmentation.core': {'yolo_v8_segmentation.core.foo': ('core.html#foo', 'yolo_v8_segmentation/core.py')},
            'yolo_v8_segmentation.data_preparation': { 'yolo_v8_segmentation.data_preparation.get_contours': ( 'data_preparation.html#get_contours',
                                                                                                               'yolo_v8_segmentation/data_preparation.py')},
            'yolo_v8_segmentation.viz_utils': { 'yolo_v8_segmentation.viz_utils.overlay_mask': ( 'viz_utils.html#overlay_mask',
                                                                                                 'yolo_v8_segmentation/viz_utils.py'),
                                                'yolo_v8_segmentation.viz_utils.overlay_mask_border_on_image': ( 'viz_utils.html#overlay_mask_border_on_image',
                                                                                                                 'yolo_v8_segmentation/viz_utils.py')}}}
