# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data_preparation.ipynb.

# %% auto 0
__all__ = ['get_contours']

# %% ../nbs/01_data_preparation.ipynb 5
def get_contours(img:np.ndarray):
    'get contours from masks'

    _, thresh = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    return cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)[0]

